[tool.poetry]
name = "meu_projeto"
version = "0.1.0"
description = ""
authors = ["lucas silva"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"